// AI 的默认参数：等于极限难度、未启用任何预设时的行为。
// 所有可调的权重、阈值、距离、时长与区间都在这里；区间写成 [最小, 最大]。
// 修改任何数值都会改变 AI 的对局行为，需按规则变更处理。

export const DEFAULT_AI_PARAMS = {
  version: 1,
  // 成套的行为开关。难度覆盖层与 legacy 预设通过它们切换代码路径。
  features: {
    characterPriority: true, // 选焦点时计入角色威胁加成
    closeout: true, // 领先与收尾窗口判断
    barrierTactics: true, // 古泉能量圈的攻防战术
    skillAimLead: true, // 定向技能按目标航向预判落点
    advancedCounterplay: true, // 困难以上的技能反制（破盾编组、躲避视野波净化）
    visionEngage: true, // 进攻时压近或远吊以保持视野交火
    formationLeash: true, // 交战角色的分离舰不得离主力过远
    indirectIntel: true, // 用可见的敌弹与敌侦察机反推敌舰位置
  },
  // 难度倍率，由难度覆盖层改写。
  difficulty: {
    reactionMult: 1, // 感知延迟倍率
    replanMult: 1, // 改航间隔倍率
  },
  // 基础行为节奏。
  profile: {
    initialScoutTimer: 1.55,
    initialFlagshipTimer: 5.6,
    moveReplanMin: 1.35,
    moveReplanMax: 2.15,
    stuckTrigger: 0.9,
    searchAdvanceWindow: 4.6,
    searchArrivalRadius: 120,
    reactionScale: 0.46,
    reactionMin: 0.03,
    reactionMax: 0.16,
    memoryLeadMultiplier: 1.28,
    probeDistanceMultiplier: 1.24,
    aggressiveScoutWindow: 0.45,
    initialSubTimers: {
      sub1: 10.5,
      sub2: 12.5,
    },
  },
  energy: {
    // 推进的能量护栏。前进4档只在能量充裕时启动，并用不同的启动/退出阈值避免
    // 3、4档在临界值附近反复切换；低能量时仍保持航行，但强制降档回能。
    gear: {
      criticalRatio: 0.14,
      lowRatio: 0.32,
      overdriveStartRatio: 0.72,
      overdriveStopRatio: 0.52,
    },
    // 能量池状态的分档阈值（占上限的比例）。
    profile: {
      highRatio: 0.7,
      lowRatio: 0.32,
      criticalRatio: 0.16,
    },
    // 能量支出许可：支出后余量不得低于底线，底线随局势调整。
    commit: {
      conserveAbove: 0.62,
      surplusDiscountMax: 0.08,
      surplusDiscount: 0.1,
    },
  },
  movement: {
    // 视野交火距离。
    engage: {
      pokeVisionMult: 1.7, // 远吊距离取敌方视野的倍数
    },
  },
  skills: {
    haruhiFlagship: {
      energyReserveWindow: 3, // 技能即将就绪的秒数内，侦察机不得抢占其能量
    },
    // 旗舰技能的下一次判断间隔（秒）：hold 为暂不施放，retry 为施放被拒，cooldown 为施放成功。
    flagshipTimers: {
      haruhiHold: [0.25, 0.45],
      conserveHold: [1.8, 3.2],
      aggressiveAbove: 0.95,
      aggressiveHold: [0.45, 0.9],
      hold: [1.2, 2.4],
      haruhiMinInterval: 0.15,
      aggressiveCooldown: [12, 17],
      cooldown: [14, 20],
      haruhiRetry: [0.18, 0.35],
      conserveRetry: [4.8, 7.4],
      aggressiveRetry: [1, 2.1],
      retry: [2.8, 5.6],
    },
    // 副舰技能的下一次判断间隔（秒），含义同旗舰。
    subTimers: {
      unavailable: [4, 7],
      conserveHold: [2, 3.6],
      aggressiveAbove: 1,
      aggressiveHold: [0.45, 1.1],
      hold: [0.9, 1.8],
      future1096AimLead: 1.05,
      haruhiMinInterval: 0.15,
      aggressiveCooldown: [12, 18],
      cooldown: [15, 22],
      conserveRetry: [4.6, 7.8],
      aggressiveRetry: [1.1, 2.2],
      retry: [2.8, 5.4],
    },
    // 旗舰技能的施放条件。
    flagship: {
      haruhiEmergencyFloor: 0.03,
      haruhiNormalFloor: 0.05,
      haruhiConserveFloor: 0.08,
      emergencyFloor: 0.1,
      normalFloor: 0.16,
      conserveFloor: 0.26,
      future1096OpenAge: 3,
      future1096OpenHull: 0.58,
      future1096OpenAggression: 0.18,
      future1096DefendHull: 0.62,
      future1096DefendPressure: 0.58,
      future1096AttackHull: 0.48,
      future1096AttackPressure: 0.42,
      future1096AttackAggression: 0.46,
      tsuruyaHull: 0.995,
      tsuruyaAggression: 0.18,
      tsuruyaUrgency: 0.34,
      asakuraChargedShotSeconds: 6,
      asakuraWaveSpeed: 480,
      asakuraPurgeMargin: 0.2,
      asakuraSearchAge: 7,
      asakuraSearchUrgency: 0.82,
    },
    // 副舰技能的施放条件。距离以本舰射程的倍数表示，age 为情报年龄（秒）。
    sub: {
      emergencyFloor: 0.08,
      normalFloor: 0.14,
      conserveFloor: 0.24,
      barrierBlockMargin: 4,
      haruhiShockRadiusDivisor: 6,
      haruhiFocusAge: 1.2,
      haruhiFocusRange: 0.9,
      haruhiAggression: 0.12,
      koizumiBreachAge: 4.2,
      koizumiBreachRange: 1.75,
      koizumiAge: 3.2,
      koizumiRange: 1.55,
      koizumiAggression: 0.14,
      future1096Age: 1.6,
      future1096Aggression: 0.18,
      kyonHull: 0.84,
      kyonRange: 1.18,
      tsuruyaAge: 7,
      tsuruyaAggression: 0.08,
      yukiScoutPriority: 0.28,
      yukiVisibleAge: 2.5,
      yukiMinScouts: 3,
      asakuraBreachAge: 4.2,
      asakuraBreachRange: 1.5,
      asakuraAge: 2.4,
      asakuraRange: 0.95,
      asakuraAggression: 0.14,
      asakuraUrgency: 0.5,
      shamisenAge: 2.2,
      shamisenRange: 1.12,
      shamisenAggression: 0.12,
    },
  },
  // 感知延迟：看见敌方实体到写入情报之间的反应时间（秒，再乘 profile.reactionScale 与难度倍率）。
  perception: {
    shipDelay: 0.14,
    wingmanDelay: 0.1,
    otherDelay: 0.08,
    mainBias: -0.02,
    jitter: 0.08,
  },
  // 焦点目标评分：对已知敌方接触逐项加权，取最高分作为主攻目标。
  focus: {
    maxAge: 8,
    proximityRangeMult: 2.4,
    proximityMin: -0.18,
    proximityMax: 0.95,
    freshnessWindow: 8,
    isolationMaxAge: 6,
    overwhelmFriendlyRadius: 300,
    overwhelmEnemyRadius: 280,
    overwhelmMin: -0.2,
    overwhelmMax: 1.4,
    typeMain: 1.28,
    typeShip: 0.9,
    typeOther: 0.32,
    visible: 0.82,
    hidden: 0.3,
    hunt: 3.2,
    uncertaintyScale: 240,
    uncertaintyMax: 1.4,
    freshness: 0.82,
    vulnerability: 1.08,
    isolation: 0.82,
    overwhelm: 0.92,
  },
  mode: {
    scores: {
      // 脱离地图边缘。
      recover: {
        edgePressure: 5,
        lowHullBelow: 0.22,
        lowHull: 1.8,
      },
      // 拉开距离回能。
      harvest: {
        energyRecoveryNeed: 3.2,
        emergencyCommit: -3.2,
        noEmergency: 0.3,
        farRangeRatio: 1.04,
        far: 0.24,
        near: -0.42,
        intelSolid: -0.55,
        intelWeak: 0.08,
        pressureDrive: 0.45,
        isolatedTarget: 0.24,
      },
      // 搜索（目前只会被强制进入，评分保留）。
      search: {
        spawn: 4.8,
        required: 2.8,
        notRequired: -0.8,
        intelSolid: -1.05,
        intelWeak: 0.72,
        trackableIntel: 0.4,
        encirclePressure: 0.34,
        energyRecoveryNeed: 0.26,
      },
      // 收拢编队。
      regroup: {
        overextended: 2.1,
        defensivePressure: 1.2,
        ownBarrierDown: 1.9,
        incomingBreaker: 1.45,
        lowEnergyBelow: 0.16,
        lowEnergy: 1.1,
        enemyBroadsideRisk: 0.8,
        energyRecoveryNeed: 0.52,
        counterCollapse: 0.4,
      },
      // 边退边打。
      kite: {
        defensivePressure: 2.1,
        ownBarrierDown: 2.35,
        incomingBreaker: 1.8,
        closeRangeBelow: 1.06,
        closeRange: 0.95,
        outnumberedBelow: 0.78,
        outnumbered: 1.1,
        enemyArc: 0.9,
        maxShipThreat: 0.18,
        energyRecoveryNeed: 0.24,
      },
      // 压上击杀。
      collapse: {
        killWindow: 3.4,
        barrierBreachWindow: 2.3,
        organizedBreach: 0.9,
        infiltrationCommit: 1.05,
        enemyBarrierUp: 1.15,
        advantage: 1.9,
        closeoutWindow: 1.6,
        intelSolid: 1,
        intelWeak: -0.55,
        safeExchange: 0.72,
        isolatedTarget: 0.92,
        counterCollapse: 0.68,
        pressureDriveAbove: 0.85,
        pressureDrive: 0.55,
        energySurplus: 0.48,
        energyRecoveryCloseout: 0.12,
        energyRecoveryNeed: 0.55,
      },
      // 抢侧舷。
      broadside: {
        window: 2.4,
        noWindow: -0.45,
        ownBarrierUp: 0.72,
        barrierBreachWindow: 0.48,
        enemyBarrierUp: 0.55,
        advantageAbove: 0.9,
        advantage: 0.82,
        killWindow: 0.55,
        arcDeficitBelow: 0.2,
        arcDeficit: 1,
        enemyBroadsideRisk: 0.9,
        energySurplus: 0.24,
        energyRecoveryNeed: 0.42,
      },
      // 前出截击。
      cutoff: {
        intelSolid: 1.3,
        intelWeak: -0.2,
        infiltrationStage: 1.35,
        infiltrationCommit: 0.72,
        organizedBreach: 0.58,
        rangeMin: 0.86,
        rangeMax: 1.95,
        inRange: 1,
        advantageAbove: 0.9,
        advantage: 0.58,
        enemyArcAbove: 1.2,
        enemyArc: 0.44,
        trackableIntel: 0.96,
        isolatedTarget: 0.34,
        energySurplus: 0.3,
        energyRecoveryNeed: 0.28,
      },
      // 常规压制（默认模式）。
      press: {
        base: 1.55,
        barrierBreachWindow: 1.85,
        organizedBreach: 0.72,
        infiltrationCommit: 0.88,
        enemyBarrierUp: 0.82,
        closeoutWindow: 1.3,
        farRangeAbove: 1.08,
        farRange: 0.92,
        advantageAbove: 0.9,
        advantage: 0.72,
        defensivePressure: 1.05,
        enemyBroadsideRisk: 0.78,
        arcAdvantageAbove: 0.2,
        arcAdvantage: 0.36,
        pressureDrive: 1.08,
        trackableIntel: 0.82,
        counterCollapse: 0.34,
        energySurplus: 0.34,
        energyRecoveryCommitted: 0.08,
        energyRecoveryNeed: 0.34,
      },
    },
    // 模式的强制条件与保持时长（秒）。强制条件优先于评分。
    choose: {
      recoverEdgePressure: 0.34,
      ownBarrierDownRange: 1.42,
      breachCollapseMinHull: 0.32,
      harvestRecoveryNeed: 0.78,
      harvestEnergyBelow: 0.12,
      harvestMinRange: 0.84,
      forcedHoldMin: 1.2,
      forcedHoldSearch: 2.8,
      forcedHoldHarvest: 3.2,
      forcedHoldOther: 2.2,
      lowHullBelow: 0.26,
      lowHullRange: 1.22,
      lowHullHold: [1.6, 2.8],
      lowEnergyThreat: 0.7,
      lowEnergyBelow: 0.12,
      lowEnergyRange: 0.96,
      lowEnergyHold: [1.8, 3],
      holdMinShort: 1.2,
      holdMinLong: 1.8,
      holdMaxLong: 3.2,
      holdMaxShort: 2.8,
    },
  },
  // 战术上下文：把观测与情报归纳成后续决策共用的判断量。
  context: {
    localRadius: 330,
    escortRadius: 240,
    localMaxAge: 8,
    escortWeight: 0.34,
    advantageBias: 0.25,
    huntContactMaxAge: 8,
    solidMaxAge: 5.5,
    solidMinConfidence: 0.42,
    searchAgeAbove: 9,
    searchConfidenceBelow: 0.26,
    killHpBelow: 0.44,
    killRange: 1.75,
    broadsideMinRange: 0.58,
    broadsideMaxRange: 1.2,
    overextendedSpread: 320,
    overextendedAdvantage: 0.92,
    defensiveAdvantage: 0.72,
    defensiveRange: 1.22,
    defensiveHull: 0.28,
    defensiveHuntedHp: 0.62,
    broadsideRiskDensity: 1.45,
    freshnessWindow: 10,
    trackableMaxAge: 13,
    trackableMinConfidence: 0.16,
    intelUrgencyVisible: 0.08,
    intelUrgencySpawn: 1.28,
    intelUrgencyBase: 0.52,
    intelUrgencyAgeScale: 9,
    intelUrgencyConfidence: 0.78,
    intelUrgencyMin: 0.3,
    intelUrgencyMax: 1.6,
    isolationMaxAge: 6,
    isolationAdvantageFloor: 0.92,
    isolationAdvantageWeight: 0.65,
    isolatedMin: -0.25,
    isolatedMax: 1.5,
    counterCollapseThreatFloor: 0.82,
    counterCollapseMax: 1.1,
    counterCollapseAdvantageMin: 0.6,
    counterCollapseAdvantageMax: 1.4,
    emergencyThreat: 0.96,
    emergencyUrgency: 0.68,
    emergencyVisibleRange: 0.92,
    emergencyTrackableRange: 0.82,
    emergencyTrackableAdvantage: 1.12,
    surplusFloor: 0.58,
    surplusSpan: 0.42,
    recoveryCeiling: 0.46,
    recoveryEmergencyFactor: 0.18,
    recoveryFactor: 0.82,
    conserveAbove: 0.78,
    mobilityBase: 0.88,
    mobilitySurplus: 0.34,
    mobilityEmergency: 0.26,
    mobilityRecovery: 0.24,
    mobilityMin: 0.62,
    mobilityMax: 1.34,
    winningHullLead: 0.08,
    closeoutEnemyHull: 0.3,
    enemyMainLead: 1.2,
    barrierContactMaxAge: 4.5,
    // 交战紧迫度。
    combatUrgency: {
      visible: 0.38,
      hidden: 0.12,
      inRangeRatio: 1.08,
      inRange: 0.32,
      killWindow: 0.38,
      pressuredRatio: 0.9,
      pressuredRange: 1.32,
      pressured: 0.12,
      trackableIntel: 0.22,
      threatFloor: 0.88,
      threat: 0.36,
      isolatedTarget: 0.18,
      max: 1.55,
    },
    // 技能施放的积极程度。
    skillAggression: {
      base: 0.38,
      energySurplus: 0.84,
      combatUrgency: 0.72,
      trackableIntel: 0.24,
      isolatedTarget: 0.18,
      energyRecoveryNeed: 0.28,
      max: 1.8,
    },
    // 侦察优先级。
    scoutPriority: {
      intelUrgency: 0.94,
      searchRequired: 0.34,
      trackableIntel: 0.34,
      hiddenHuntTarget: 0.42,
      threatFloor: 0.9,
      threat: 0.45,
      combatUrgency: 0.22,
      energyRecoveryNeed: 0.28,
      max: 1.8,
    },
    // 包围展开的力度。
    encirclePressure: {
      base: 0.82,
      freshness: 0.46,
      trackableIntel: 0.42,
      searchRequired: 0.32,
      isolatedTarget: 0.24,
      min: 0.6,
      max: 1.65,
    },
    // 主动压制的驱动力。
    pressureDrive: {
      advantageFloor: 0.76,
      advantageMax: 1.1,
      advantage: 1.34,
      energySurplus: 0.78,
      freshnessFloor: 0.18,
      freshnessMax: 0.82,
      freshness: 0.74,
      killWindow: 0.82,
      trackableIntel: 0.64,
      emergencyCommit: 0.28,
      counterCollapse: 0.22,
      isolatedTarget: 0.26,
      huntTargetVisible: 0.62,
      huntOvercommit: 0.7,
      energyRecoveryNeed: 0.32,
    },
  },
  // 分离决策。时间单位为秒，距离以旗舰射程的倍数表示。
  split: {
    huntMinHull: 0.34,
    huntMinEnergy: 0.1,
    // 分离效用：舰体状态、视野优势与角色偏置之和。
    utility: {
      visionEdgeScale: 52,
      visionEdgeMin: -0.18,
      visionEdgeMax: 0.7,
      yukiBias: 0.46,
      future1096Bias: 0.28,
      asakuraBias: 0.24,
      shamisenBias: 0.22,
      otherBias: 0.12,
    },
    // 一级分离（sub1）。
    level1: {
      barrierAfter: 4,
      barrierMinHull: 0.54,
      weakMainHull: 0.32,
      weakMainEnergy: 0.18,
      weakFleetHull: 0.42,
      weakEnergy: 0.14,
      weakThreat: 1.15,
      weakAfter: 30,
      weakMinRange: 1.5,
      searchUtility: 1.3,
      searchHoldHigh: 10,
      searchHoldLow: 14,
      earlyUtilityHigh: 1.34,
      earlyHigh: 6.2,
      earlyUtilityMid: 1.08,
      earlyMid: 7.8,
      earlyLow: 9.2,
      isolated: 0.34,
      freshness: 0.44,
      advantageUtility: 1.08,
      advantageHigh: 0.72,
      advantageLow: 0.82,
      range: 1.9,
    },
    // 二级分离（sub2）。
    level2: {
      barrierAfter: 8,
      barrierMinHull: 0.58,
      weakMainHull: 0.38,
      weakMainEnergy: 0.22,
      weakFleetHull: 0.5,
      weakEnergy: 0.2,
      weakThreat: 1.08,
      weakAfter: 58,
      weakAdvantage: 0.9,
      intelUtility: 1.18,
      intelHoldHigh: 22,
      intelHoldLow: 30,
      earlyUtilityHigh: 1.28,
      earlyHigh: 13.5,
      earlyUtilityMid: 1.04,
      earlyMid: 16.5,
      earlyLow: 18.5,
      isolated: 0.42,
      advantageUtility: 1.12,
      advantageHigh: 0.86,
      advantageLow: 0.98,
      range: 1.35,
    },
  },
  scout: {
    // 是否发射侦察机。
    launch: {
      yukiDesiredActive: 4,
      yukiMaxActive: 6,
      yukiEmergencyEnergy: 0.24,
      yukiPriority: 0.82,
      yukiThreat: 0.92,
      emergencyEnergy: 0.34,
      priority: 0.12,
    },
    // 侦察节拍（秒）与能量底线：launched 为发射成功后的间隔，noEnergy/rejected 为未能发射，hold 为决定不发射。
    timers: {
      planRefresh: 0.4,
      urgentIntel: 0.88,
      urgentThreat: 0.94,
      yukiEmergencyFloor: 0.08,
      yukiNormalFloor: 0.12,
      yukiConserveFloor: 0.2,
      emergencyFloor: 0.12,
      normalFloor: 0.18,
      conserveFloor: 0.28,
      highPriority: 1.05,
      highThreat: 0.92,
      launchedUrgent: [3.1, 4.8],
      launchedTrackable: [3.6, 5.4],
      launchedConserve: [5.2, 7.4],
      launched: [4.5, 6.8],
      noEnergyYuki: [1.2, 2.2],
      noEnergy: [2.2, 3.8],
      rejectedEmergency: [0.9, 1.8],
      rejected: [1.4, 2.8],
      holdYukiConserve: [1.4, 2.2],
      holdYuki: [0.8, 1.4],
      holdConserve: [2.2, 3.4],
      hold: [1.2, 2.2],
    },
  },
  intel: {
    // 情报外推：按来源衰减置信度、增长不确定度，并沿预测航向漂移。
    projection: {
      leadFactor: 0.78,
      radarFreshMin: 0.8,
      radarDefaultLife: 3,
      radarDefaultConfidence: 0.42,
      radarConfidenceDecay: 0.055,
      radarConfidenceMin: 0.12,
      radarConfidenceMax: 0.88,
      spawnConfidence: 0.42,
      spawnConfidenceDecay: 0.028,
      spawnConfidenceMin: 0.14,
      memoryConfidence: 0.88,
      memoryConfidenceDecay: 0.05,
      memoryConfidenceMin: 0.18,
      radarDefaultUncertainty: 60,
      radarUncertaintyGrowth: 16,
      radarUncertaintyMin: 8,
      radarUncertaintyMax: 280,
      spawnUncertainty: 90,
      spawnUncertaintyGrowth: 20,
      spawnUncertaintyMax: 230,
      memoryUncertainty: 14,
      memoryUncertaintyGrowth: 28,
      memoryUncertaintyConfidence: 75,
      memoryUncertaintyMax: 210,
      forwardDriftBase: 0.24,
      forwardDriftNoise: 0.32,
      lateralDrift: 0.78,
    },
  },
  // 战力估值：把敌方接触与己方舰船折算成可比较的战力，用于局部优势、威胁与孤立度。
  value: {
    contactHpMin: 0.08,
    unknownScoutHp: 0.4,
    unknownWingmanHp: 0.8,
    unknownShipHp: 0.82,
    contactConfidenceMin: 0.2,
    combatScout: 0.21,
    scout: 0.08,
    scoutHiddenFactor: 0.75,
    wingman: 0.42,
    wingmanHiddenFactor: 0.86,
    contactMainRole: 1.28,
    contactSubRole: 0.98,
    rangeRef: 520,
    rangeFactorMin: 0.84,
    contactRangeFactorMax: 1.18,
    fireRateFloor: 0.22,
    contactDpsRef: 58,
    dpsFactorMin: 0.78,
    contactDpsFactorMax: 1.32,
    contactHpBase: 0.34,
    contactHpWeight: 0.66,
    shipHiddenFactor: 0.92,
    shipHpMin: 0.08,
    shipMainRole: 1.24,
    shipAuxRole: 0.72,
    shipRangeFactorMax: 1.2,
    shipDpsRef: 60,
    shipDpsFactorMax: 1.34,
    shipHpBase: 0.38,
    shipHpWeight: 0.62,
    shipEnergyBase: 0.48,
    shipEnergyWeight: 0.52,
    friendlyReach: 1.2,
    friendlyShipFalloffMin: 0.25,
    friendlyWingman: 0.36,
    friendlyWingmanHpMin: 0.2,
    friendlyAircraftFalloffMin: 0.22,
    friendlyCombatScout: 0.21,
    enemyReach: 1.25,
    enemyFalloffMin: 0.22,
    isolationRadius: 240,
    isolationBase: 1.2,
    isolationMin: -0.4,
    isolationMax: 1.1,
    vitalityHp: 0.7,
    vitalityEnergy: 0.3,
    fragileHp: 0.4,
    fragileEnergy: 0.18,
    healthyHp: 0.7,
    healthyEnergy: 0.34,
    threatDefaultRange: 500,
    threatRangeMargin: 70,
    threatAircraftRange: 300,
    threatFalloffMin: 0.24,
    supportFloor: 0.1,
    supportRadius: 250,
    supportSelfDiscount: 0.22,
    overwhelmedDanger: 0.96,
  },
  detached: {
    // 前探舰选择：视野优势、航速与角色偏置之和超过 minScore 才指派。
    intelLead: {
      visionMarginScale: 55,
      visionMarginMin: -0.2,
      visionMarginMax: 0.85,
      visionBase: 160,
      visionScale: 70,
      visionMax: 0.65,
      speedBase: 33,
      speedScale: 8,
      speedMin: -0.1,
      speedMax: 0.3,
      yukiBias: 0.9,
      asakuraBias: 0.32,
      future1096Bias: 0.18,
      searchBias: 0.18,
      minScore: 1,
    },
    // 分离舰的后撤需求。
    retreat: {
      hpCeiling: 0.48,
      hpWeight: 2.4,
      energyCeiling: 0.26,
      energyWeight: 1.8,
      closeRange: 0.92,
      close: 0.22,
      enemyBroadsideRisk: 0.16,
      defensivePressure: 0.14,
      max: 1.8,
    },
  },
};
